---
title: "EDRM 718 Final Exam Score Form"
output:
  html_document:
    df_print: paged
---

**Student: Adam Brown**

The scored elements are itemized below, along with the total number of possible points for each element. Points were awarded on a scale, with zero points indicating that the element was not addressed and maximum points indicating that not only was it addressed but done completely correctly.

***

#### Repository (10 points)

**Repository development and organization; commits and documentation of commits**

Very nice! A nice trail of commits along the way with a separate commit for each part. You need to populate your readme file with the purpose and structure of this repo.

**9/10**

***

#### Organization and Neatness (10 points)

**Readability, organization, and neatness of output**

This is very nicely organized and easy to read.

**10/10**

***

#### Functions (15 points)

**Function development, documentation, and sourcing**

These are well-written functions, though you are missing documentation at the top of each function to describe arguments and usage.

**13/15**

***

#### Data Preparation (20 points)

**Data screening and preparation**

You used the tidyverse to do some problem checking, you tidied data, and you joined the data sets. The primary weakness here is that you did not do some of the necessary manual checking. You failed to catch an ID problem. You also didn't check the range or categories of variables to make sure that everything looks good.

**16/20**

***

#### Graphical Displays (15 points)

**Visual displays of major outcomes of interest, including formatting and labeling**

Beautiful and correct graphs!

**15/15**

***

#### Descriptive Statistics (15 points)

**Descriptive statistics, tables, and narrative addressing research questions**

You created reasonable statistics to accompany some graphs, yet a clear ommission is a table of descriptive statistics, perhaps overall and by discipline.

**12/15**

***

#### Inferential Statistics (15 points)

**Inferential statistics and narrative addressing research questions (15 points)**

Very nice work here! I like that you obtained separate slopes to investigate the second question and recognized that this is interaction, though a more direct answer to the question would have been with an overall test of the interaction.

**14/15**

***

#### Total (100 points)

You have already become an excellent R user/programmer. I hope that you find these skills useful throughout your professional career.

**89/100**

***
